model_dir: D:/luke/lte_geo/save/_train_swinir-lte_geo
model_name: unwilling_cocoa # unwilling_cocoa #joint_fly #unwilling_cocoa #joint_fly ###holy_molding # beige_ottoman  #average_aerator # artificial_observatory #beige_ottoman
inference_output_dir: # blank or Custom path
num_workers: 2
rgb_range: 2 # noddyverse min max clip +-5000 to range [-1, 1]
eval_bsize: 360_000 #360_000 # Reduce RAM usage? num points per model call
limit_to_plots: True  # subset dataset to "interesting" plots, OR don't plot and calc metrics
plot_samples: [[17, 20, 70, 91, 143, 185, 199, 200], [0, 1]]
custom_grids: False
eval_bsize: 360_000 # Reduce RAM usage? num points per model call
real_inference_size: 128

test_dataset:
  batch_size: 1
  dataset:
    name: noddyverse_dataset
    args:
      root_path: C:/Users/Public/scratch/Noddy_1M
      noddylist: C:/Users/Public/scratch/Noddy_10k/models_10k.csv
      events: 
      hr_line_spacing: 4 # 4, so gridded shape is same as gt.
      sample_spacing: 1
      heading: NS
      load_magnetics: True # Norm [+-5000]
      load_gravity: False # Norm [400,500]
      norm: [-5000,5000]
  wrapper:
    name: noddyverse_wrapper
    args:
      crop: False
      inp_size: 45
      scale_min: 1
      scale_max: 9
  batch_size: 1
