model_dir: D:/luke/lte_geo/save/_train_swinir-lte_geo
model_name: beige_ottoman
inference_output_dir: # blank or Custom path
num_workers: 0
rgb_range: 2 # noddyverse min max clip +-5000 to range [-1, 1]
limit_to_plots: True
plot_samples: [95, 19, 59, 79, 86, 116, 209, 265, 317, 319, 320,321,322,323,324,325,326,327,328,329,330,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415]
custom_grids: True
eval_bsize: 360_000 # Reduce RAM usage? num points per model call

test_dataset:
  dataset:
    name: noddyverse_dataset
    args:
      root_path: D:/luke/Noddy_data/noddyverse_test_data
      hr_line_spacing: 4 # 4, so gridded shape is same as gt.
      sample_spacing: 1
      heading: NS
      norm: 5000 # NotImplemented - TODO, norm, unnorm instantiation
  wrapper:
    name: noddyverse_wrapper
    args:
      crop: False
      inp_size: 45
      scale_min: 2
      scale_max: 9
  batch_size: 1
