test_dataset:
  dataset:
    name: noddyverse_dataset
    args:
      root_path: D:/luke/Noddy_data/noddyverse_test_data
      hr_line_spacing: 4 # 4, so gridded shape is same as gt.
      sample_spacing: 20
      heading: NS
  wrapper:
    name: noddyverse_wrapper
    args:
      is_val: True
      inp_size: 48
      scale_min: 4
      scale_max: 4
  batch_size: 1
eval_type: noddyverse-4
eval_bsize: 30000

num_workers: 0
rgb_range: 2 #noddyverse min max clip +-5000 to range [-1, 1]

show_scale_samples_not_eval: False
visually_nice_test_samples: [19, 59, 79, 86, 95, 116, 209, 265, 317, 319]
# 116 shows an example of classic line pattern rotation

data_norm:
  inp: {sub: [0], div: [1]}
  gt: {sub: [0], div: [1]}