model_dir: D:/luke/lte_geo/save/_train_swinir-lte_geo
model_name: beige_ottoman
num_workers: 0
rgb_range: 2 # noddyverse min max clip +-5000 to range [-1, 1]
eval_type: noddyverse-3
eval_bsize: 160_000
limit_to_plots: True
scale_range: False
plot_samples: [19, 59, 79, 86, 95, 116, 209, 265, 317, 319, 320,321,322,323,324,325,326,327,328,329,330,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415]

test_dataset:
  dataset:
    name: noddyverse_dataset
    args:
      root_path: D:/luke/Noddy_data/noddyverse_test_data
      hr_line_spacing: 4 # 4, so gridded shape is same as gt.
      sample_spacing: 20
      heading: NS
  wrapper:
    name: noddyverse_wrapper
    args:
      crop: False
      inp_size: 60
      scale_min: 3
      scale_max: 3
  batch_size: 1

data_norm:
  inp: {sub: [0], div: [1]}
  gt: {sub: [0], div: [1]}