train_dataset:
  dataset:
    name: noddyverse_dataset
    args:
      root_path: D:/luke/Noddy_data/noddyverse_train_data
      repeat: 20
      cache: in_memory
  wrapper:
    name: noddyverse_wrapper
    args:
      inp_size: 48
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 32

val_dataset:
  dataset:
    name: noddyverse_dataset
    args:
      root_path: D:/luke/Noddy_data/noddyverse_val_data
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: noddyverse_wrapper
    args:
      inp_size: 48
      scale_max: 4
      sample_q: 2304
  batch_size: 32

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: lte
  args:
    encoder_spec:
      name: swinir
      args:
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256]
    hidden_dim: 256

optimizer:
  name: adam
  args:
    lr: 2.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [500, 800, 900, 950]
  gamma: 0.5

epoch_val: 1
epoch_save: 100

resume: ./save/_train_swinir-lte/epoch-last.pth