dataset_grid_param:
  load_magnetics: True
  load_gravity: False
  load_geology: False

train_dataset:
  dataset:
    name: noddyverse_dataset
    args:
      root_path: D:/luke/Noddy_data/noddyverse_train_data
      repeat: 20
      limit_length: 800
      hr_line_spacing: 4
      sample_spacing: 20
      heading: NS
  wrapper:
    name: noddyverse_wrapper
    args:
      inp_size: 24
      scale_max: 4 #TODO 5 or higher scale
  batch_size: 8

val_dataset:
  dataset:
    name: noddyverse_dataset
    args:
      repeat: 1
      root_path: D:/luke/Noddy_data/noddyverse_val_data
      hr_line_spacing: 5
      sample_spacing: 20
      heading: NS
  wrapper:
    name: noddyverse_wrapper
    args:
      inp_size: 24
      scale_max: 4
  batch_size: 8

data_norm:
  inp: {sub: [0], div: [1]}
  gt: {sub: [0], div: [1]}

model:
  name: lte
  args:
    encoder_spec:
      name: swinir
      args:
        no_upsampling: true
        in_chans: 1
    imnet_spec:
      name: mlp
      args:
        out_dim: 1
        hidden_list: [256, 256, 256]
    hidden_dim: 256

optimizer:
  name: adam
  args:
    lr: 2.e-4
epoch_max: 50
multi_step_lr:
  milestones: [10, 20, 30, 40]
  gamma: 0.5

epoch_val: 1
epoch_save: 26

num_workers: 8
rgb_range: 2 #noddyverse min max clip +-5000

# resume: ./save/_train_swinir-lte/epoch-last.pth
## train.py#49 - change resume logic