use_comet: True
use_amp_scaler: False  # Currently causes NaN
use_amp_autocast: False  # Seems to make results bad lol
num_workers: 10 # ~6+ on 10900KF / 3090
eval_type: noddyverse-4
plot_samples: [209, 221, 232, 237, 244, 248, 256, 253, 253, 254]
rgb_range: 1  # noddyverse min max clip +-5000
shave: 15
model_dir: D:/luke/phd/ch2/ltegeo/save/_train_swinir-lte_geo/
resume: # major_fish_9316 # disappointed_neutron_9322 # colossal_south_9912
only_resume_weights: False

train_dataset:
  dataset:
    name: noddyverse_dataset
    args:
      repeat: 1  # number of times to iterate entire dataset - i.e. epochs (but of the below slice)
      use_dset_slice: [0, 960_000]  # restrict dataset to [n:m]  # ~ 1 hour / 100k samples
      root_path: "C:/Users/Public/scratch/Noddy_1M" #C:/Users/Public/scratch/noddyverse/train
      noddylist: "C:/Users/Public/scratch/Noddy_1M/models.csv"
      blocklist: "C:/Users/Public/scratch/Noddy_10k/models_10k.csv"  # Don't allow use of models in the 10k test set.
      events:
      # hr_line_spacing: lls / scale # 4  # array coords. 1 == 20 m Noddyverse
      gt_patch_size: 200
      input_cell_size: 20 # m
      lr_line_spacing: 400 # m  # 20 * 20 m == 400 m
      sample_spacing: 20 # m
      # cs_fac: 5  # Hardcoded to 5
      heading: NS
      norm: [-10000, 10000]
      load_magnetics: True
      load_gravity: False
  wrapper:
    name: noddyverse_wrapper
    args:
      augmentations:
        flip: False
        rotate: False
        sample: False
      inp_size: 48 # Currently hardcoded at 48 due to bug
      sample_q: 2304 # (inp_size * min(scale))**2
      scales: [4] # [2, 4, 5]  # only support 2, 4, 10.
  batch_size: 8

val_dataset:
  dataset:
    name: noddyverse_dataset
    args:
      root_path: "C:/Users/Public/scratch/Noddy_1M"
      repeat: 1
      use_dset_slice: [-1001, -1]  # [n:m] slice notation, can be negative
      noddylist: "C:/Users/Public/scratch/Noddy_1M/models.csv"
      blocklist: "C:/Users/Public/scratch/Noddy_10k/models_10k.csv" 
      gt_patch_size: 200
      input_cell_size: 20
      lr_line_spacing: 400 # m  # 20 * 20 m == 400 m
      sample_spacing: 20
      # cs_fac: 4  # Hardcoded to 4
      heading: NS
      norm: [-10000, 10000]
      load_magnetics: True
      load_gravity: False
      events:
  wrapper:
    name: noddyverse_wrapper
    args:
      inp_size: 48 # Currently hardcoded at 48 due to bug
      sample_q: # sample_q destroys image structure, so don't use in Val
      scales: [4] #[2, 4, 5]
  batch_size: 8
loss_fn: l1

model:
  name: lte
  args:
    encoder_spec:
      name: swinir
      args:
        # upsampler: none
        no_upsampling: True # Possibly unused in swinir
        in_chans: 1
    imnet_spec:
      name: mlp
      args:
        out_dim: 1
        hidden_list: [256, 256, 256]
    hidden_dim: 256

optimizer:
  name: adam
  args:
    lr: 1.e-4

epoch_max: 10
epoch_val: 1
epoch_save:
scheduler:
  # multi_step_lr:
  #   milestones: [5,6,7,8,9]
  #   gamma: 0.5
  one_cycle_lr:
    max_lr: 1.e-4
