dataset_grid_param:
  load_magnetics: True
  load_gravity: False
  load_geology: False

train_dataset:
  dataset:
    name: noddyverse_dataset
    args:
      root_path: D:/luke/Noddy_data/noddyverse_train_data
      repeat: 1
      limit_length: 2500
      hr_line_spacing: 2 # array coords
      sample_spacing: 20 # spatial coords
      heading: NS
  wrapper:
    name: noddyverse_wrapper
    args:
      inp_size: 48 # LR input size
      scale_max: 4 #up to 10, hardcoded to exclude 7
      # cs_fac: 4 # Hardcoded to 4. If you set to 5, exclude scale 8.
  batch_size: 8

val_dataset:
  dataset:
    name: noddyverse_dataset
    args:
      repeat: 1
      root_path: D:/luke/Noddy_data/noddyverse_val_data
      hr_line_spacing: 4
      sample_spacing: 20
      heading: NS
  wrapper:
    name: noddyverse_wrapper
    args:
      inp_size: 48
      scale_max: 4
  batch_size: 8

eval_type: noddyverse-4

data_norm:
  inp: {sub: [0], div: [1]}
  gt: {sub: [0], div: [1]}

model:
  name: lte
  args:
    encoder_spec:
      name: swinir
      args:
        no_upsampling: true
        in_chans: 1
    imnet_spec:
      name: mlp
      args:
        out_dim: 1
        hidden_list: [256, 256, 256]
    hidden_dim: 256

optimizer:
  name: adam
  args:
    lr: 2.e-4
epoch_max: 10
multi_step_lr:
  milestones: [1, 2, 3, 4, 5, 6, 7, 8]
  gamma: 0.5

epoch_val: 1
epoch_save: 9

num_workers: 4
rgb_range: 2 #noddyverse min max clip +-5000
use_comet: True
# resume: ./save/_train_swinir-lte/epoch-last.pth
## train.py#49 - change resume logic